services:
  - type: web
    name: resume-matcher-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: node server/server.js
    envVars:
      - key: PYTHON_BACKEND_URL
        value: https://resume-matcher-fastapi.onrender.com

  - type: web
    name: resume-matcher-fastapi
    env: python
    plan: free
    buildCommand: pip install -r similarity/requirements.txt
    startCommand: uvicorn similarity.main:app --host 0.0.0.0 --port 8000
